//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESummer2022KarnaukhAL4338.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Orders_Services = new HashSet<Orders_Services>();
        }
    
        public int ID { get; set; }
        public string Order_code { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.TimeSpan> Order_time { get; set; }
        public Nullable<int> Client_code { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public Nullable<System.TimeSpan> Rental_time { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Services> Orders_Services { get; set; }
    }
}
